# Settings for API to player and bank accounts
api:
    # Bank settings
    bank:
        # All bank support can be disabled if desired
        enabled: true

        # No real reason to set anything but 0.0 here, as players would
        # abuse it. Included for completeness
        initial_balance: 0.0

    # Player settings
    player:
        # Amount of money a player gets when logging in or going
        # to a location for the first time
        initial_balance: 10.00
        
    # Currency settings for controlling how amounts are printed
    # in response to commands
    currency:
        numerical_format: "#,##0.00"
        name:
            plural: "Simoleons"
            singular: "Simoleon"
            
# Sets the location translator used for mapping player location into 
# account location
# Options include:
# * multiverse - Uses Multiverse-Inventories plugin groups for locations
#   Without Multiverse-Inventories plugin loaded the behavior is the same
#   as the per_world translator
# * multiinv - Uses the MultiInv plugin, similar to Multiverse-Inventories
# * worldinventories - Uses the WorldInventories plugin, similar to Multiverse-Inventories
# * per_world - One accounts location per world
# * myworlds - Use the My Worlds plugin for seperating economies
# * global - One location per server, ie one global account location

location:
  translator: multiverse
  
  # Translator options: not all translators have options yet, but sections
  # are included for completeness
  
  # global has the option of setting the name for the global location
  global:
    name: "global"
    
  # No options for these translators
  multiverse: null
  per_world: null
  
  # Support for Factions accounts. Name is the location name
  # to apply to the factions account. This should be different
  # than all other location names to avoid possible conflicts.
  factions_support:
    enabled: True
    name: "factions"
            
# Settings for commands            
commands:
    # Settings for /top command
    top:
      # Number of wealthiest players to show when the /top command is used
      number: 5
    
      # Whether to include banks in player wealth
      include_banks: true 
    
# Storage settings
storage:
    # Settings that only apply if the YAML storage method is being used
    yaml:
        # Name of the file in the plugins/SDFEconomy where accounts are stored 
        filename: "accounts.yaml"

        # Commit delay is the number of ticks to wait till commiting updates
        # A commit delay of 0 means the file is saved on every update
        # If the delay is negative then no commits are done till the plugin
        # is disabled
        # There are 20 ticks per second, so the default delay is 60/20 = 3 seconds.
        commit_delay: 60
 
# If language and optionaly country are defined then the plugin will try and
# find a localization file matching. These files must already be included in the plugin.
# By default the locale is commented out so that the default configured by the system
# is used. You can define only language without country, but the default will still
# be used if you only define country.
#
# Look at which CommandTranslation*.properties files are available:
# https://github.com/omwah/SDFEconomy/tree/master/src/main/resources
# The language and country code will be in the name of the file
#
# Language codes:
# http://www.loc.gov/standards/iso639-2/englangn.html
# Country codes:
# http://www.iso.org/iso/prods-services/iso3166ma/02iso-3166-code-lists/country_names_and_code_elements
locale:
    # language: en
    # country: US
