# This is a sample plugin.yml
# For more infomration refer to http://wiki.bukkit.org/Plugin_YAML
main: com.github.omwah.SDFEconomy.SDFEconomy
name: ${project.name}
version: ${project.version}
author: Omwah
description: ${project.description}

commands:
    sdfeconomy:
        description: Manipulate and query player balances and banks
        aliases: [economy, econ]
        usage: /sdfeconomy help - For more information
    balance:
        description: "Retrieve a player's account balance"
        usage: /balance ? - For more information
    pay:
        description: "Pay another player"
        usage: /pay ? - For more information

permissions:
    sdfeconomy.*:
        description: Give access to all SDFEconomy commands
        children:
          sdfeconomy.use_account: true
          sdfeconomy.use_bank: true
          sdfeconomy.pay_players: true
          sdfeconomy.admin: true 
    sdfeconomy.use_account:
        description: Allow usage of a player account
        default: true
    sdfeconomy.use_bank:
        description: Allow usage of bank accounts
        default: true
    sdfeconomy.pay_players:
        description: Allow paying other players
        default: true
    sdfeconomy.admin:
        description: Allow access to administration commands
        default: op
