# This is a sample plugin.yml
# For more infomration refer to http://wiki.bukkit.org/Plugin_YAML
main: com.github.omwah.SDFEconomy.SDFEconomy
name: ${project.name}
version: ${project.version}
author: Omwah
description: ${project.description}

commands:
  economy:
    description: Manipulate and query player balances and banks
    aliases: [econ]
    usage: |

permissions:
  econ.*:
    description: All SDFEconomy permissions
    default: op
    children:
      econ.common.*: true
